### ISSUE TITLE
Not obfuscating emails

### ISSUE THREAD

**Issue by vignesh511989** [xini/silverstripe-email-obfuscator#7]
Hi,

I'm trying to use this module to obfuscate emails. 

I installed the module using composer and ran dev/build. do i need to do anything extra to configure this.

SS version - 4.9.1
PHP version - 8.0

Thanks 
Vignesh

<img width="1388" alt="Screen Shot 2021-12-15 at 9 18 42 AM" src="https://user-images.githubusercontent.com/59625151/146073793-2b470974-a6f2-4dfd-b3c6-86515f973e33.png">

**Comment by xini** [comment]
Hi Vignesh,

The module uses JavaScript to reinstate the email addresses after the site has loaded (see https://github.com/xini/silverstripe-email-obfuscator/blob/master/client/src/javascript/email-obfuscator.js). 

Can you please deactivate JavaScript in your browser and look at the page source then? The link should look something like this:

```
<a href="#" rel="nofollow" data-eo="grfg#tznvy#pbz" title="E-Mail not displayed without javascript." data-eo-text="true">[E-Mail not displayed]</a>
```

Please let me know if that worked.

**Comment by vignesh511989** [comment]
Hi,

Yes. that works. thanks for looking into this.

**Comment by xini** [comment]
No worries.
